name = "cloudflare-d1-adapter"
main = "src/index.ts"
compatibility_date = "2026-01-08"
workers_dev = false

[[services]]
binding = "INTERNAL_GATEWAY_SERVICE"
service = "internal-gateway"

[vars]
ENV = "production"

[[durable_objects.bindings]]
name = "TENANT_DATABASE_REGISTRY"
class_name = "TenantDatabaseRegistryDO"

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TenantDatabaseRegistryDO"]

[env.dev]
workers_dev = false

[[env.dev.services]]
binding = "INTERNAL_GATEWAY_SERVICE"
service = "internal-gateway-dev"

[[env.dev.durable_objects.bindings]]
name = "TENANT_DATABASE_REGISTRY"
class_name = "TenantDatabaseRegistryDO"

[env.dev.vars]
ENV = "dev"

[env.production]
